// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: servicing.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ServicingService_GetServiceById_FullMethodName = "/ServicingService/GetServiceById"
)

// ServicingServiceClient is the client API for ServicingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicingServiceClient interface {
	GetServiceById(ctx context.Context, in *GetServiceByIdRequest, opts ...grpc.CallOption) (*Servicing, error)
}

type servicingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServicingServiceClient(cc grpc.ClientConnInterface) ServicingServiceClient {
	return &servicingServiceClient{cc}
}

func (c *servicingServiceClient) GetServiceById(ctx context.Context, in *GetServiceByIdRequest, opts ...grpc.CallOption) (*Servicing, error) {
	out := new(Servicing)
	err := c.cc.Invoke(ctx, ServicingService_GetServiceById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicingServiceServer is the server API for ServicingService service.
// All implementations should embed UnimplementedServicingServiceServer
// for forward compatibility
type ServicingServiceServer interface {
	GetServiceById(context.Context, *GetServiceByIdRequest) (*Servicing, error)
}

// UnimplementedServicingServiceServer should be embedded to have forward compatible implementations.
type UnimplementedServicingServiceServer struct {
}

func (UnimplementedServicingServiceServer) GetServiceById(context.Context, *GetServiceByIdRequest) (*Servicing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceById not implemented")
}

// UnsafeServicingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicingServiceServer will
// result in compilation errors.
type UnsafeServicingServiceServer interface {
	mustEmbedUnimplementedServicingServiceServer()
}

func RegisterServicingServiceServer(s grpc.ServiceRegistrar, srv ServicingServiceServer) {
	s.RegisterService(&ServicingService_ServiceDesc, srv)
}

func _ServicingService_GetServiceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicingServiceServer).GetServiceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicingService_GetServiceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicingServiceServer).GetServiceById(ctx, req.(*GetServiceByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicingService_ServiceDesc is the grpc.ServiceDesc for ServicingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ServicingService",
	HandlerType: (*ServicingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceById",
			Handler:    _ServicingService_GetServiceById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servicing.proto",
}
