// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: timeslot.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TimeslotService_FindExistTimeslot_FullMethodName      = "/TimeslotService/FindExistTimeslot"
	TimeslotService_CheckAvailableTimeslot_FullMethodName = "/TimeslotService/CheckAvailableTimeslot"
	TimeslotService_UpdateStatusTimeslot_FullMethodName   = "/TimeslotService/UpdateStatusTimeslot"
)

// TimeslotServiceClient is the client API for TimeslotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeslotServiceClient interface {
	FindExistTimeslot(ctx context.Context, in *FindTimeslotRequest, opts ...grpc.CallOption) (*TimeslotList, error)
	CheckAvailableTimeslot(ctx context.Context, in *CheckAvailableTimeslotRequest, opts ...grpc.CallOption) (*Timeslot, error)
	UpdateStatusTimeslot(ctx context.Context, in *UpdateStatusTimeslotRequest, opts ...grpc.CallOption) (*Timeslot, error)
}

type timeslotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeslotServiceClient(cc grpc.ClientConnInterface) TimeslotServiceClient {
	return &timeslotServiceClient{cc}
}

func (c *timeslotServiceClient) FindExistTimeslot(ctx context.Context, in *FindTimeslotRequest, opts ...grpc.CallOption) (*TimeslotList, error) {
	out := new(TimeslotList)
	err := c.cc.Invoke(ctx, TimeslotService_FindExistTimeslot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeslotServiceClient) CheckAvailableTimeslot(ctx context.Context, in *CheckAvailableTimeslotRequest, opts ...grpc.CallOption) (*Timeslot, error) {
	out := new(Timeslot)
	err := c.cc.Invoke(ctx, TimeslotService_CheckAvailableTimeslot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeslotServiceClient) UpdateStatusTimeslot(ctx context.Context, in *UpdateStatusTimeslotRequest, opts ...grpc.CallOption) (*Timeslot, error) {
	out := new(Timeslot)
	err := c.cc.Invoke(ctx, TimeslotService_UpdateStatusTimeslot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeslotServiceServer is the server API for TimeslotService service.
// All implementations should embed UnimplementedTimeslotServiceServer
// for forward compatibility
type TimeslotServiceServer interface {
	FindExistTimeslot(context.Context, *FindTimeslotRequest) (*TimeslotList, error)
	CheckAvailableTimeslot(context.Context, *CheckAvailableTimeslotRequest) (*Timeslot, error)
	UpdateStatusTimeslot(context.Context, *UpdateStatusTimeslotRequest) (*Timeslot, error)
}

// UnimplementedTimeslotServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTimeslotServiceServer struct {
}

func (UnimplementedTimeslotServiceServer) FindExistTimeslot(context.Context, *FindTimeslotRequest) (*TimeslotList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindExistTimeslot not implemented")
}
func (UnimplementedTimeslotServiceServer) CheckAvailableTimeslot(context.Context, *CheckAvailableTimeslotRequest) (*Timeslot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAvailableTimeslot not implemented")
}
func (UnimplementedTimeslotServiceServer) UpdateStatusTimeslot(context.Context, *UpdateStatusTimeslotRequest) (*Timeslot, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatusTimeslot not implemented")
}

// UnsafeTimeslotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeslotServiceServer will
// result in compilation errors.
type UnsafeTimeslotServiceServer interface {
	mustEmbedUnimplementedTimeslotServiceServer()
}

func RegisterTimeslotServiceServer(s grpc.ServiceRegistrar, srv TimeslotServiceServer) {
	s.RegisterService(&TimeslotService_ServiceDesc, srv)
}

func _TimeslotService_FindExistTimeslot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindTimeslotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeslotServiceServer).FindExistTimeslot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeslotService_FindExistTimeslot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeslotServiceServer).FindExistTimeslot(ctx, req.(*FindTimeslotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeslotService_CheckAvailableTimeslot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAvailableTimeslotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeslotServiceServer).CheckAvailableTimeslot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeslotService_CheckAvailableTimeslot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeslotServiceServer).CheckAvailableTimeslot(ctx, req.(*CheckAvailableTimeslotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeslotService_UpdateStatusTimeslot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusTimeslotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeslotServiceServer).UpdateStatusTimeslot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeslotService_UpdateStatusTimeslot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeslotServiceServer).UpdateStatusTimeslot(ctx, req.(*UpdateStatusTimeslotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeslotService_ServiceDesc is the grpc.ServiceDesc for TimeslotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeslotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TimeslotService",
	HandlerType: (*TimeslotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindExistTimeslot",
			Handler:    _TimeslotService_FindExistTimeslot_Handler,
		},
		{
			MethodName: "CheckAvailableTimeslot",
			Handler:    _TimeslotService_CheckAvailableTimeslot_Handler,
		},
		{
			MethodName: "UpdateStatusTimeslot",
			Handler:    _TimeslotService_UpdateStatusTimeslot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timeslot.proto",
}
