// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: timeslot.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timeslot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime  string `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	BookedDate string `protobuf:"bytes,3,opt,name=booked_date,json=bookedDate,proto3" json:"booked_date,omitempty"`
	Status     string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	BarberId   int32  `protobuf:"varint,5,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
	CreatedAt  int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  int64  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Timeslot) Reset() {
	*x = Timeslot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timeslot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeslot) ProtoMessage() {}

func (x *Timeslot) ProtoReflect() protoreflect.Message {
	mi := &file_timeslot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeslot.ProtoReflect.Descriptor instead.
func (*Timeslot) Descriptor() ([]byte, []int) {
	return file_timeslot_proto_rawDescGZIP(), []int{0}
}

func (x *Timeslot) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Timeslot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Timeslot) GetBookedDate() string {
	if x != nil {
		return x.BookedDate
	}
	return ""
}

func (x *Timeslot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Timeslot) GetBarberId() int32 {
	if x != nil {
		return x.BarberId
	}
	return 0
}

func (x *Timeslot) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Timeslot) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type TimeslotList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeslots []*Timeslot `protobuf:"bytes,1,rep,name=timeslots,proto3" json:"timeslots,omitempty"`
}

func (x *TimeslotList) Reset() {
	*x = TimeslotList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeslotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeslotList) ProtoMessage() {}

func (x *TimeslotList) ProtoReflect() protoreflect.Message {
	mi := &file_timeslot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeslotList.ProtoReflect.Descriptor instead.
func (*TimeslotList) Descriptor() ([]byte, []int) {
	return file_timeslot_proto_rawDescGZIP(), []int{1}
}

func (x *TimeslotList) GetTimeslots() []*Timeslot {
	if x != nil {
		return x.Timeslots
	}
	return nil
}

type UpdateStatusTimeslotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateStatusTimeslotRequest) Reset() {
	*x = UpdateStatusTimeslotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusTimeslotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusTimeslotRequest) ProtoMessage() {}

func (x *UpdateStatusTimeslotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeslot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusTimeslotRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusTimeslotRequest) Descriptor() ([]byte, []int) {
	return file_timeslot_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStatusTimeslotRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStatusTimeslotRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FindTimeslotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime  string `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	BookedDate string `protobuf:"bytes,2,opt,name=booked_date,json=bookedDate,proto3" json:"booked_date,omitempty"`
	Status     string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	BarberId   int32  `protobuf:"varint,4,opt,name=barber_id,json=barberId,proto3" json:"barber_id,omitempty"`
}

func (x *FindTimeslotRequest) Reset() {
	*x = FindTimeslotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindTimeslotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTimeslotRequest) ProtoMessage() {}

func (x *FindTimeslotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeslot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTimeslotRequest.ProtoReflect.Descriptor instead.
func (*FindTimeslotRequest) Descriptor() ([]byte, []int) {
	return file_timeslot_proto_rawDescGZIP(), []int{3}
}

func (x *FindTimeslotRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *FindTimeslotRequest) GetBookedDate() string {
	if x != nil {
		return x.BookedDate
	}
	return ""
}

func (x *FindTimeslotRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindTimeslotRequest) GetBarberId() int32 {
	if x != nil {
		return x.BarberId
	}
	return 0
}

type CheckAvailableTimeslotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CheckAvailableTimeslotRequest) Reset() {
	*x = CheckAvailableTimeslotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeslot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAvailableTimeslotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailableTimeslotRequest) ProtoMessage() {}

func (x *CheckAvailableTimeslotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeslot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailableTimeslotRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailableTimeslotRequest) Descriptor() ([]byte, []int) {
	return file_timeslot_proto_rawDescGZIP(), []int{4}
}

func (x *CheckAvailableTimeslotRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_timeslot_proto protoreflect.FileDescriptor

var file_timeslot_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xcd, 0x01, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x62, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x37, 0x0a, 0x0c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x27, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x22, 0x45, 0x0a, 0x1b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x8a, 0x01, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x6f, 0x6b, 0x65,
	0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f,
	0x6f, 0x6b, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x61, 0x72, 0x62, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2f, 0x0a,
	0x1d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0xd7,
	0x01, 0x0a, 0x0f, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3a, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x45, 0x78, 0x69, 0x73, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x14, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x1e, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x6c, 0x6f, 0x74, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x1c, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timeslot_proto_rawDescOnce sync.Once
	file_timeslot_proto_rawDescData = file_timeslot_proto_rawDesc
)

func file_timeslot_proto_rawDescGZIP() []byte {
	file_timeslot_proto_rawDescOnce.Do(func() {
		file_timeslot_proto_rawDescData = protoimpl.X.CompressGZIP(file_timeslot_proto_rawDescData)
	})
	return file_timeslot_proto_rawDescData
}

var file_timeslot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_timeslot_proto_goTypes = []any{
	(*Timeslot)(nil),                      // 0: Timeslot
	(*TimeslotList)(nil),                  // 1: TimeslotList
	(*UpdateStatusTimeslotRequest)(nil),   // 2: UpdateStatusTimeslotRequest
	(*FindTimeslotRequest)(nil),           // 3: FindTimeslotRequest
	(*CheckAvailableTimeslotRequest)(nil), // 4: CheckAvailableTimeslotRequest
}
var file_timeslot_proto_depIdxs = []int32{
	0, // 0: TimeslotList.timeslots:type_name -> Timeslot
	3, // 1: TimeslotService.FindExistTimeslot:input_type -> FindTimeslotRequest
	4, // 2: TimeslotService.CheckAvailableTimeslot:input_type -> CheckAvailableTimeslotRequest
	2, // 3: TimeslotService.UpdateStatusTimeslot:input_type -> UpdateStatusTimeslotRequest
	1, // 4: TimeslotService.FindExistTimeslot:output_type -> TimeslotList
	0, // 5: TimeslotService.CheckAvailableTimeslot:output_type -> Timeslot
	0, // 6: TimeslotService.UpdateStatusTimeslot:output_type -> Timeslot
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_timeslot_proto_init() }
func file_timeslot_proto_init() {
	if File_timeslot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timeslot_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Timeslot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslot_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TimeslotList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslot_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateStatusTimeslotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslot_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FindTimeslotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeslot_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CheckAvailableTimeslotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timeslot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timeslot_proto_goTypes,
		DependencyIndexes: file_timeslot_proto_depIdxs,
		MessageInfos:      file_timeslot_proto_msgTypes,
	}.Build()
	File_timeslot_proto = out.File
	file_timeslot_proto_rawDesc = nil
	file_timeslot_proto_goTypes = nil
	file_timeslot_proto_depIdxs = nil
}
