// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: previewimage.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PreviewImageService_GetPreviewImageByUser_FullMethodName = "/PreviewImageService/GetPreviewImageByUser"
	PreviewImageService_SavePreviewImage_FullMethodName      = "/PreviewImageService/SavePreviewImage"
)

// PreviewImageServiceClient is the client API for PreviewImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PreviewImageServiceClient interface {
	GetPreviewImageByUser(ctx context.Context, in *GetPreviewImageRequest, opts ...grpc.CallOption) (*PreviewImageList, error)
	SavePreviewImage(ctx context.Context, in *SavePreviewImageRequest, opts ...grpc.CallOption) (*PreviewImage, error)
}

type previewImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPreviewImageServiceClient(cc grpc.ClientConnInterface) PreviewImageServiceClient {
	return &previewImageServiceClient{cc}
}

func (c *previewImageServiceClient) GetPreviewImageByUser(ctx context.Context, in *GetPreviewImageRequest, opts ...grpc.CallOption) (*PreviewImageList, error) {
	out := new(PreviewImageList)
	err := c.cc.Invoke(ctx, PreviewImageService_GetPreviewImageByUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *previewImageServiceClient) SavePreviewImage(ctx context.Context, in *SavePreviewImageRequest, opts ...grpc.CallOption) (*PreviewImage, error) {
	out := new(PreviewImage)
	err := c.cc.Invoke(ctx, PreviewImageService_SavePreviewImage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreviewImageServiceServer is the server API for PreviewImageService service.
// All implementations should embed UnimplementedPreviewImageServiceServer
// for forward compatibility
type PreviewImageServiceServer interface {
	GetPreviewImageByUser(context.Context, *GetPreviewImageRequest) (*PreviewImageList, error)
	SavePreviewImage(context.Context, *SavePreviewImageRequest) (*PreviewImage, error)
}

// UnimplementedPreviewImageServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPreviewImageServiceServer struct {
}

func (UnimplementedPreviewImageServiceServer) GetPreviewImageByUser(context.Context, *GetPreviewImageRequest) (*PreviewImageList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPreviewImageByUser not implemented")
}
func (UnimplementedPreviewImageServiceServer) SavePreviewImage(context.Context, *SavePreviewImageRequest) (*PreviewImage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SavePreviewImage not implemented")
}

// UnsafePreviewImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreviewImageServiceServer will
// result in compilation errors.
type UnsafePreviewImageServiceServer interface {
	mustEmbedUnimplementedPreviewImageServiceServer()
}

func RegisterPreviewImageServiceServer(s grpc.ServiceRegistrar, srv PreviewImageServiceServer) {
	s.RegisterService(&PreviewImageService_ServiceDesc, srv)
}

func _PreviewImageService_GetPreviewImageByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreviewImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreviewImageServiceServer).GetPreviewImageByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreviewImageService_GetPreviewImageByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreviewImageServiceServer).GetPreviewImageByUser(ctx, req.(*GetPreviewImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreviewImageService_SavePreviewImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePreviewImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreviewImageServiceServer).SavePreviewImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreviewImageService_SavePreviewImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreviewImageServiceServer).SavePreviewImage(ctx, req.(*SavePreviewImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PreviewImageService_ServiceDesc is the grpc.ServiceDesc for PreviewImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreviewImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PreviewImageService",
	HandlerType: (*PreviewImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPreviewImageByUser",
			Handler:    _PreviewImageService_GetPreviewImageByUser_Handler,
		},
		{
			MethodName: "SavePreviewImage",
			Handler:    _PreviewImageService_SavePreviewImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "previewimage.proto",
}
