syntax = "proto3";

option go_package = "/pb";

import "google/protobuf/wrappers.proto";

message PreviewImage {
    int32 id = 1;
    string generated_img = 2;
    int64 created_at = 3;
    int32 account_id = 4;
    string self_img = 5;
    string shape_img = 6;
    string color_img = 7;
}

message GetPreviewImageRequest {
    int32 account_id = 1;
}

message PreviewImageList {
    repeated PreviewImage preview_images = 1;
}

service PreviewImageService {
    rpc GetPreviewImageByUser(GetPreviewImageRequest) returns (PreviewImageList) {};
}
