version: '3.8'

services:
  app:
    build: .
    ports:
      - "8008:8008"
    environment:
      - MONGO_URI=mongodb://mongo:2717/user_management
      - DB_USER=postgres
      - DB_PASSWORD=tr1nhtu@n
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - DB_NAME_ACCOUNT=barber_management
      - DB_NAME_SERVICE=service_management
      - DB_NAME_BOOKING=booking_management
      - DB_NAME_TIMESLOT=timeslot_management
      - DB_NAME_PREVIEW_IMAGE=preview_image_management
      - DB_NAME_CRITERIA=criteria_management
      - DB_NAME_RESULT=result_management
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=mysecretpassword
      - SECRET_JWT=SuperSecureKey
      - SECRET_REFRESH=SuperSecureRefreshKey
      - SCHEDULED_TIME=01:22:00
    depends_on:
      - mongo
      - redis
      - postgres
    networks:
      - kong-network

  mongo:
    image: mongo:latest
    ports:
      - "2717:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tom
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - kong-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "mysecretpassword"]
    networks:
      - kong-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tr1nhtu@n
      POSTGRES_DB: barber_management
    networks:
      - kong-network

  # Kong database service
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    networks:
      - kong-network
    ports:
      - "5433:5432"

  kong-migrations:
    image: kong:3.7.0
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
    command: ["kong", "migrations", "bootstrap"]
    networks:
      - kong-network

  # Kong API Gateway service
  kong:
    image: kong:3.7.0
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"  # Kong Proxy Port
      - "8443:8443"
      - "8001:8001"  # Kong Admin Port
      - "8002:8002"  # Kong GUI Port
      - "8444:8444"
    depends_on:
      - kong-database
      - kong-migrations
    networks:
      - kong-network

networks:
  kong-network:
    driver: bridge